### ISSUE TITLE
Thread in Sent does not contain any emails

### ISSUE THREAD

**Issue by let4be** [lavab/api#107]
Threads id: J8Hruu9FUctqJugIid6D, PnxwrffOOIaGQT2JW849, uB0TEHN0cs2FMCLEt4b1

**Comment by andreis** [comment]
Env?

**Comment by let4be** [comment]
.co
this is old bug but still doesn't fixed

**Comment by let4be** [comment]
but now I tested it on .com(as .co is dead) and it's the same

**Comment by andreis** [comment]
@pzduniak please fix this as soon as possible (i.e. after the server setup)

**Comment by let4be** [comment]
This seems to be fixed now. I can see all emails in the Sent threads.
Please confirm someone else so we could close this ;)

**Comment by pzduniak** [comment]
Everything works for me, so I'm closing it now.
