### ISSUE TITLE
The wonders of duplicated labels

### ISSUE THREAD

**Issue by let4be** [lavab/api#111]
@piggyslasher somehow managed to create an account with duplicated primary labels...
So he now has multiple Inbox, Sent, Starred, Spam etc labels...

Where? Takes place on .com
When? first noticed 1 day before, confirmed now
His owner id is: ytut9R6fngoXCmeicW51
example of label ids(Inbox): GW6V8NXNMzoYlCMDz8Ci, TGg7nZhU7PADQCMHlZ7m

Need to fix this as soon as possible

P.S. my code does not create labels with one exception - drafts
https://github.com/lavab/web/blob/develop/src/js/apps/AppLavaboom/services/inbox.js#L108-108

**Comment by piggyslasher** [comment]
this might be because i went through the signup process a few times because i thought the key generation was hanging (it was take minutes at a time).
