### ISSUE TITLE
Threads.list labels filter

### ISSUE THREAD

**Issue by let4be** [lavab/api#113]
Filter out threads with labels Spam/Trash when we request a list of threads outside of Spam/Trash

I'm going to mark threads as Spam just by adding Spam label and preserve all original labels so later thread could be easily restored from spam

**Comment by let4be** [comment]
Important: it should respect offset/limit - the whole point of this enchancement

**Comment by pzduniak** [comment]
So thats pretty much advanced query generation for labels, I'll sort it out today with #118

**Comment by pzduniak** [comment]
Implemented in 8c9be3c4fdb854ba134274bd5edbf674be95dfbd
