### ISSUE TITLE
Moving thread to trash/spam and thread.is_read flag

### ISSUE THREAD

**Issue by let4be** [lavab/api#122]
Currently we mark thread as read after a certain timeout(4 sec)
if user moves the thread faster to his trash/spam thread stays unread

we do not show it in the Inbox, but labels.list has no idea about new labels filtering Inbox -Trash -Spam...

**Comment by let4be** [comment]
I could just issue a separate request but I try to keep request count as low as possible

**Comment by pzduniak** [comment]
It took me a while to parse contents of this issue, but I think I know what's wrong. On it!

**Comment by pzduniak** [comment]
Actually I'm not sure what's the issue here, but I transformed input in threads.update into pointers and I compare them with nil before trying to do anything with them. Hopefully it fixes whatever you meant here.
