### ISSUE TITLE
Thread matching bug

### ISSUE THREAD

**Issue by let4be** [lavab/api#127]
1. Send email to yourself with subject "hi"(thread_1)
2. Send email from gmail to lavaboom with subject "hi"
Email from gmail ends up to be in the thread_1 and members field does not contain any information about this "merge"

Expected: email should go to another thread
where? .com

**Comment by pzduniak** [comment]
I knew that I forgot about one part of the algorithm. Will fix it after
deploying hipache+redis
16 kwi 2015 11:33 "let4be" <notifications@github.com> napisał(a):

**Comment by pzduniak** [comment]
Let's move to #129
