### ISSUE TITLE
Threads are identified by subject line if no references exist

### ISSUE THREAD

**Issue by mlooz** [lavab/api#129]
This sometimes creates problems.
Steps to reproduce:
1. Write email from first external account (alice@example.com) with subject "Invoice" to lavaboom account
2. Write email from second external account (bob@example.com) with subject "Invoice" to lavaboom account

What happens:
Emails from Alice and Bob are shown in one thread, even though they don't have anything to do with each other.

This also happens in practice, for example all "Undelivered emails returned to sender" messages are aggregated into one thread.

Appears to be duplicate of #127, sorry.

**Comment by mlooz** [comment]
Suggested solution:
Remove lines 697 - 714 of https://github.com/lavab/mailer/blob/master/handler/handler.go

**Comment by pzduniak** [comment]
Added a members check in 23e44e585790884bc469e7cc87deb112e63bac1f. Please check if it's fine now, then I might also add a time check.

**Comment by pzduniak** [comment]
I'll just close it for now. We'll reopen if someone notices a bug related to it.

**Comment by andreis** [comment]
> andreis removed the in progress label 4 hours ago
Wtf? I didn't do that, is it because of CodeTree?

**Comment by pzduniak** [comment]
im just hitting here stealing your cookies and removing labels

**Comment by mlooz** [comment]
The initial bug of https://github.com/lavab/web/issues/552 still occurs when both emails are from the same sender.
Steps to reproduce:
1. Send email with subject "Invoice" from external account to lavaboom account
2. Move email to trash within lavaboom
3. Send second email with subject "Invoice" from same external account

What happens: second email is also sorted into trash, never occuring in inbox.

**Comment by pzduniak** [comment]
I'll solve that issue in as lavab/web#552

2015-05-17 23:08 GMT+02:00 mlooz <notifications@github.com>:

> The initial bug of lavab/web#552 <https://github.com/lavab/web/issues/552>
> still occurs when both emails are from the same sender.
> Steps to reproduce:
> 1. Send email with subject "Invoice" from external account to lavaboom
> account
> 2. Move email to trash within lavaboom
> 3. Send second email with subject "Invoice" from same external account
>
> What happens: second email is also sorted into trash, never occuring in
> inbox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavab/api/issues/129#issuecomment-102858496>.
>



-- 
Piotr Zduniak
piotr@zduniak.net
http://zduniak.net

**Comment by andreis** [comment]
That sounds like a `mailer` issue, especially if the emails actually appear in the same thread.
