### ISSUE TITLE
Need endpoint that will simply mirror requested headers

### ISSUE THREAD

**Issue by let4be** [lavab/api#141]
Needed for: https://github.com/lavab/web/issues/814

Background: http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference

**Comment by pzduniak** [comment]
https://api.lavaboom.com/headers

what am i doing with my life

**Comment by let4be** [comment]
@andreis won't be happy with this enhancement :D :P

**Comment by andreis** [comment]
Great simple solution :+1:
