### ISSUE TITLE
/GET files with filtering by tags returns `Internal error (code FI/LI/03)`

### ISSUE THREAD

**Issue by let4be** [lavab/api#156]
`/files?tags=draft&sort=-date_modified&offset=0&limit=15` returns `Internal error (code FI/LI/03)`
on staging branch

**Comment by andreis** [comment]
This seems to be a 24-day old issue. Is it still relevant @let4be?

**Comment by let4be** [comment]
wups, it was resolved by Piotr few weeks ago
closing
