### ISSUE TITLE
Multiple duplicated thread ids when using reply to

### ISSUE THREAD

**Issue by let4be** [lavab/api#90]
I ended up with 4 threads id ex1MSUrqCsuSCXwjnXz8 in my inbox after having a short conversation with myself(gmail inbox)
help...

**Comment by let4be** [comment]
@pzduniak what is the status?...
This is blocking issue it ruins part of functionality on client side, could you please resolve this?

**Comment by andreis** [comment]
@let4be: @pzduniak is doing server stuff until Monday, so we don't get *more* downtime in the future and have a better infrastructure

**Comment by pzduniak** [comment]
Possibly fixed in fce903f2e6d4f75717e834634f25ff989e30cd1d. Requires testing.

**Comment by pzduniak** [comment]
Confirmed fixed in 275e53802d5205a256a148d84676f569e92cd214
